apiVersion: v1
kind: HorizontalPodAutoscaler
metadata:
  name: knote-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: knote
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric: rps
        target: 5
